import React, { Component } from "react";
import { DayPilot, DayPilotScheduler } from "daypilot-pro-react";
import Zoom from "./zoom";

class Scheduler extends Component {
  deadlines = [
    {
      name: "syllabus.html",
      folder: "course_info",
      type: "syllabus",
      grading: "participation",
      points: "na",
      start_or_posted: "8/15/22",
      end_or_due: "12/9/22",
      module: "none",
      title: "Syllabus",
      reference: "na",
    },
    {
      name: "module1",
      folder: "na",
      type: "module",
      grading: "na",
      points: "na",
      start_or_posted: "8/22/22",
      end_or_due: "8/26/22",
      module: "module1",
      title: "Foundations",
      reference: "na",
    },
    {
      name: "01-01.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "8/22/22",
      end_or_due: "8/22/22",
      module: "module1",
      title: "What is computer graphics",
      reference: "na",
    },
    {
      name: "01-02.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "8/24/22",
      end_or_due: "8/24/22",
      module: "module1",
      title: "Computer graphics pipeline",
      reference: "na",
    },
    {
      name: "01-03.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "partitipation",
      points: "1",
      start_or_posted: "8/26/22",
      end_or_due: "8/26/22",
      module: "module1",
      title: "Computer graphics hardware",
      reference: "na",
    },
    {
      name: "assignment_01.html",
      folder: "assignment",
      type: "assignment",
      grading: "assignment",
      points: "10",
      start_or_posted: "8/15/22",
      end_or_due: "8/29/22",
      module: "module1",
      title: "first assignment",
      reference: "na",
    },
    {
      name: "module2",
      folder: "na",
      type: "module",
      grading: "na",
      points: "na",
      start_or_posted: "8/29/22",
      end_or_due: "9/2/22",
      module: "module2",
      title: "Linear algebra",
      reference: "na",
    },
    {
      name: "02-01.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "8/29/31",
      end_or_due: "8/29/31",
      module: "module2",
      title: "Linear algebra p1",
      reference: "na",
    },
    {
      name: "02-02.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "8/31/22",
      end_or_due: "8/31/22",
      module: "module2",
      title: "Linear algebra p2",
      reference: "na",
    },
    {
      name: "02_03.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/2/22",
      end_or_due: "9/2/22",
      module: "module2",
      title: "Linear algebra p3",
      reference: "na",
    },
    {
      name: "01.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "8/29/31",
      end_or_due: "8/29/31",
      module: "module2",
      title: "Intro",
      reference: "na",
    },
    {
      name: "02.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "8/29/31",
      end_or_due: "8/29/31",
      module: "module2",
      title: "Vectors",
      reference: "na",
    },
    {
      name: "03.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "8/31/22",
      end_or_due: "8/31/22",
      module: "module2",
      title: "Span",
      reference: "na",
    },
    {
      name: "04.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "8/31/22",
      end_or_due: "8/31/22",
      module: "module2",
      title: "Linear Transformations",
      reference: "na",
    },
    {
      name: "05.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/2/22",
      end_or_due: "9/2/22",
      module: "module2",
      title: "Matrix Multiplication",
      reference: "na",
    },
    {
      name: "06.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/2/22",
      end_or_due: "9/2/22",
      module: "module2",
      title: "3D transformations",
      reference: "na",
    },
    {
      name: "assignment_02.html",
      folder: "assignment",
      type: "assignment",
      grading: "assignment",
      points: "10",
      start_or_posted: "9/2/22",
      end_or_due: "9/9/22",
      module: "module2",
      title: "Linear algebra review",
      reference: "na",
    },
    {
      name: "module3",
      folder: "na",
      type: "module",
      grading: "na",
      points: "na",
      start_or_posted: "9/7/22",
      end_or_due: "9/7/22",
      module: "module3",
      title: "Rasterization",
      reference: "na",
    },
    {
      name: "03-01.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/7/22",
      end_or_due: "9/7/22",
      module: "module3",
      title: "How to draw lines",
      reference: "na",
    },
    {
      name: "03-02.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/9/22",
      end_or_due: "9/9/22",
      module: "module3",
      title: "How to draw shapes",
      reference: "na",
    },
    {
      name: "07.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/7/22",
      end_or_due: "9/7/22",
      module: "module3",
      title: "Determinant",
      reference: "na",
    },
    {
      name: "08.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/7/22",
      end_or_due: "9/7/22",
      module: "module3",
      title: "Inverse Matrices",
      reference: "na",
    },
    {
      name: "09.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/7/22",
      end_or_due: "9/7/22",
      module: "module3",
      title: "Nonsquare Marices",
      reference: "na",
    },
    {
      name: "10.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/9/22",
      end_or_due: "9/9/22",
      module: "module3",
      title: "Dot Product",
      reference: "na",
    },
    {
      name: "11.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/9/22",
      end_or_due: "9/9/22",
      module: "module3",
      title: "Cross product",
      reference: "na",
    },
    {
      name: "12.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/9/22",
      end_or_due: "9/9/22",
      module: "module3",
      title: "Cross product",
      reference: "na",
    },
    {
      name: "assignment_03.html",
      folder: "assignment",
      type: "assignment",
      grading: "assignment",
      points: "10",
      start_or_posted: "9/9/22",
      end_or_due: "9/26/22",
      module: "module3",
      title: "Rasterization exercise",
      reference: "na",
    },
    {
      name: "module4",
      folder: "na",
      type: "module",
      grading: "na",
      points: "na",
      start_or_posted: "9/12/22",
      end_or_due: "9/16/22",
      module: "module4",
      title: "Transformations",
      reference: "na",
    },
    {
      name: "04-01.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/12/22",
      end_or_due: "9/12/22",
      module: "module4",
      title: "Transformations p1",
      reference: "na",
    },
    {
      name: "04-02.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/14/22",
      end_or_due: "9/14/22",
      module: "module4",
      title: "Transformations p2",
      reference: "na",
    },
    {
      name: "04-03.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/16/22",
      end_or_due: "9/16/22",
      module: "module4",
      title: "Transformations p3",
      reference: "na",
    },
    {
      name: "13.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/12/22",
      end_or_due: "9/12/22",
      module: "module4",
      title: "Cross product as transformation",
      reference: "na",
    },
    {
      name: "14.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/12/22",
      end_or_due: "9/12/22",
      module: "module4",
      title: "Cramer's rule",
      reference: "na",
    },
    {
      name: "15.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/14/22",
      end_or_due: "9/14/22",
      module: "module4",
      title: "Change of bias",
      reference: "na",
    },
    {
      name: "16.html",
      folder: "pages",
      type: "inclass",
      grading: "participation",
      points: "1",
      start_or_posted: "9/16/22",
      end_or_due: "9/16/22",
      module: "module4",
      title: "Eigenvectors",
      reference: "na",
    },
    {
      name: "assignment_04.html",
      folder: "assignment",
      type: "assignment",
      grading: "assignment",
      points: "10",
      start_or_posted: "9/16/22",
      end_or_due: "9/23/22",
      module: "module4",
      title: "Transformations exercise",
      reference: "na",
    },
    {
      name: "module5",
      folder: "na",
      type: "module",
      grading: "na",
      points: "na",
      start_or_posted: "9/19/22",
      end_or_due: "9/23/22",
      module: "module5",
      title: "Projection",
      reference: "na",
    },
    {
      name: "05-01.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/19/22",
      end_or_due: "9/19/22",
      module: "module5",
      title: "Projection p1",
      reference: "na",
    },
    {
      name: "05-02.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/21/22",
      end_or_due: "9/21/22",
      module: "module5",
      title: "Projection p2",
      reference: "na",
    },
    {
      name: "05-03.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/23/22",
      end_or_due: "9/23/22",
      module: "module5",
      title: "Projection p3",
      reference: "na",
    },
    {
      name: "assignment_05.html",
      folder: "assignment",
      type: "assignment",
      grading: "assignment",
      points: "10",
      start_or_posted: "9/23/22",
      end_or_due: "9/30/22",
      module: "module5",
      title: "Projection exercises",
      reference: "na",
    },
    {
      name: "module6",
      folder: "na",
      type: "module",
      grading: "na",
      points: "na",
      start_or_posted: "9/26/22",
      end_or_due: "9/30/22",
      module: "module6",
      title: "Texture mapping",
      reference: "na",
    },
    {
      name: "06-01.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/26/22",
      end_or_due: "9/26/22",
      module: "module6",
      title: "Texture mapping",
      reference: "na",
    },
    {
      name: "06-02.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/28/22",
      end_or_due: "9/28/22",
      module: "module6",
      title: "Texture mapping",
      reference: "na",
    },
    {
      name: "06-03.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "9/30/22",
      end_or_due: "9/30/22",
      module: "module6",
      title: "Texture mapping",
      reference: "na",
    },
    {
      name: "assignment_06.html",
      folder: "assignment",
      type: "assignment",
      grading: "assignment",
      points: "10",
      start_or_posted: "9/30/22",
      end_or_due: "10/5/22",
      module: "module5",
      title: "Texture mapping exercises",
      reference: "na",
    },
    {
      name: "module7",
      folder: "na",
      type: "module",
      grading: "na",
      points: "na",
      start_or_posted: "10/3/22",
      end_or_due: "10/14/22",
      module: "module7",
      title: "Color",
      reference: "na",
    },
    {
      name: "07-02.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "10/3/22",
      end_or_due: "10/3/22",
      module: "module7",
      title: "Color",
      reference: "na",
    },
    {
      name: "07-03.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "10/5/22",
      end_or_due: "10/5/22",
      module: "module7",
      title: "Color",
      reference: "na",
    },
    {
      name: "assignment_07.html",
      folder: "assignment",
      type: "assifgnment",
      grading: "assignment",
      points: "10",
      start_or_posted: "10/5/22",
      end_or_due: "10/14/22",
      module: "na",
      title: "Color",
      reference: "na",
    },
    {
      name: "module8",
      folder: "na",
      type: "module",
      grading: "na",
      points: "na",
      start_or_posted: "10/12/22",
      end_or_due: "10/16/22",
      module: "module8",
      title: "Light and shadow",
      reference: "na",
    },
    {
      name: "08-02.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "10/12/22",
      end_or_due: "10/12/22",
      module: "module8",
      title: "Light and shador",
      reference: "na",
    },
    {
      name: "08-03.pptx",
      folder: "presentations",
      type: "lecture",
      grading: "participation",
      points: "1",
      start_or_posted: "10/14/22",
      end_or_due: "10/14/22",
      module: "module8",
      title: "Light and shadow",
      reference: "na",
    },
    {
      name: "assignment08.html",
      folder: "assignment",
      type: "assignment",
      grading: "assignment",
      points: "10",
      start_or_posted: "10/14/22",
      end_or_due: "10/26/22",
      module: "module8",
      title: "Light and shadow",
      reference: "na",
    },
    {
      name: "midterm.html",
      folder: "exams",
      type: "exams",
      grading: "exams",
      points: "100",
      start_or_posted: "10/26/22",
      end_or_due: "10/26/22",
      module: "module8",
      title: "Midterm exam",
      reference: "na",
    },
  ];

  constructor(props) {
    super(props);

    this.state = {
      // infiniteScrollingEnabled: true,

      startDate: "2022-11-01",
      endDate: "2022-12-01",
      days: 31,
      scale: "Day",
      eventHeight: 30,
      cellWidth: 50,
      timeHeaders: [{ groupBy: "Month" }, { groupBy: "Day", format: "d" }],
      cellWidthSpec: "Auto",
      resources: [
        { name: "Computer Graphics", id: "A" },
        { name: "Senior Design", id: "B" },
        { name: "UI C", id: "C" },
      ],
      events: [
        {
          id: 1,
          text: "Light and shador",
          start: "2022-11-02T00:00:00",
          end: "2022-11-02T00:00:00",
          resource: "A",
        },

        {
          id: 2,
          name: "08-02.pptx",
          folder: "presentations",
          resource: "lecture",
          grading: "participation",
          points: "1",
          start: "2022-11-02T00:00:00",
          end: "2022-11-02T00:00:00",
          module: "module8",
          text: "Light and shador",
          reference: "na",
        },
      ],
    };
  }

  zoomChange(args) {
    switch (args.level) {
      case "month":
        this.setState({
          startDate: DayPilot.Date.today().firstDayOfMonth(),
          days: 300,
          scale: "Day",
        });
        break;
      case "week":
        this.setState({
          startDate: DayPilot.Date.today().firstDayOfWeek(),
          days: 7,
          scale: "Day",
        });
        break;
      default:
        throw new Error("Invalid zoom level");
    }
  }

  render() {
    const { ...config } = this.state;
    return (
      <div>
        <div className="toolbar">
          <Zoom onChange={(args) => this.zoomChange(args)} />
        </div>

        <DayPilotScheduler
          {...config}
          onEventMoved={(args) => {
            console.log(
              "Event moved: ",
              args.e.data.id,
              args.newStart,
              args.newEnd,
              args.newResource
            );
          }}
          onTimeRangeSelected={(args) => {
            DayPilot.Modal.prompt("New event name", "Event").then((modal) => {
              this.scheduler.clearSelection();
              if (!modal.result) {
                return;
              }
              this.scheduler.events.add({
                id: DayPilot.guid(),
                text: modal.result,
                start: args.start,
                end: args.end,
                resource: args.resource,
              });
            });
          }}
          ref={(component) => {
            this.scheduler = component && component.control;
          }}
        />
      </div>
    );
  }
}

export default Scheduler;
